version: "3"

services:
  website:
    build: .
    container_name: paul-website
    command: bash -c "jekyll serve --watch --port 4000 --livereload --verbose"
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
